import type { Resource } from './types';

export const resourceData: Resource[] = [
  {
    slug: 'salle-des-tilleuls',
    category: 'SALLE DE RÉUNION',
    description: 'Un espace lumineux pour vos réunions et ateliers en petit groupe.',
    image: '/resources/salle-tilleuls.jpeg',
    meta: '12 personnes · Usage associatif',
    name: 'Salle des Tilleuls',
    availability: 'Disponible le 15 octobre',
  },
  {
    slug: 'atelier-des-possibles',
    category: 'SALLE POLYVALENTE',
    description: 'Un lieu modulable pour créer, partager et préparer vos événements.',
    image: '/resources/atelier.jpeg',
    meta: '24 personnes · Remise en état',
    name: 'Atelier des possibles',
    availability: 'Disponible le 15 octobre',
  },
  {
    slug: 'videoprojecteur-mobile',
    category: 'MATÉRIEL',
    description: 'Projetez vos présentations avec un équipement facile à installer.',
    image: '/resources/projecteur.jpeg',
    meta: 'Retrait sur place · Retour sous 24 h',
    name: 'Vidéoprojecteur mobile',
    availability: 'Disponible le 15 octobre',
  },
  {
    slug: 'jardin-partage',
    category: 'ESPACE EXTÉRIEUR',
    description: 'Un cadre convivial pour les rencontres et activités de plein air.',
    image: '/resources/jardin.jpeg',
    meta: '20 personnes · Jusqu’à 18 h',
    name: 'Jardin partagé',
    availability: 'Créneaux limités',
    limited: true,
  },
  {
    slug: 'studio-des-voix',
    category: 'SALLE SPÉCIALISÉE',
    description: 'Un espace calme pour enregistrer un podcast ou une interview.',
    image: '/resources/studio.jpeg',
    meta: '4 personnes · Initiation requise',
    name: 'Studio des voix',
    availability: 'Disponible le 15 octobre',
  },
  {
    slug: 'kit-de-sonorisation',
    category: 'MATÉRIEL',
    description: 'Une solution compacte pour sonoriser vos petites rencontres.',
    image: '/resources/sonorisation.jpeg',
    meta: 'Retrait sur place · Formation requise',
    name: 'Kit de sonorisation',
    availability: 'Créneaux limités',
    limited: true,
  },
];
